# Generated by Django 6.1.1 on 2026-09-25 21:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artworks', '0008_schema_reserved'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('amount_pence', models.PositiveIntegerField()),
                ('delivery_pence', models.PositiveIntegerField()),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('buyer_name', models.CharField(blank=True, max_length=200)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('shipping_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='artworks.artwork')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
