# Generated by Django 6.1.1 on 2026-09-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_schema_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_pence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('expired', 'Expired'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
