# Generated by Django 6.1.1 on 2026-09-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_schema_refunds'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('online', 'Online'), ('exhibition', 'Exhibition'), ('private', 'Private sale')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='venue',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
