"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

import environ
import sentry_sdk
from django.templatetags.static import static
from django.urls import reverse_lazy

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')


SECRET_KEY = env('SECRET_KEY')
DEBUG = env.bool('DEBUG', default=False)
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=False)
SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False)
SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=False)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

NOINDEX = env.bool('NOINDEX', default=False)

REDIS_URL = env('REDIS_URL', default='')

CACHES = {
    'default': {'BACKEND': 'django.core.cache.backends.redis.RedisCache', 'LOCATION': REDIS_URL}
    if REDIS_URL
    else {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'},
}

RATELIMIT_IP_META_KEY = None if DEBUG else 'HTTP_X_FORWARDED_FOR'


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django_vite',
    'inertia',
    'gesso.accounts',
    'gesso.artworks',
    'gesso.commerce',
    'gesso.content',
    'gesso.enquiries',
    'gesso.web',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'inertia.middleware.InertiaMiddleware',
    'gesso.web.middleware.share_site',
    'gesso.web.middleware.noindex',
    'gesso.web.middleware.preview',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gesso.web.context_processors.site',
                'gesso.web.context_processors.sentry',
            ],
        },
    },
]

UNFOLD = {
    'SITE_TITLE': 'config.dashboard.site_name',
    'SITE_HEADER': 'config.dashboard.site_name',
    'SITE_SUBHEADER': 'Studio',
    'SITE_SYMBOL': 'palette',
    'SITE_FAVICONS': [
        {'rel': 'icon', 'type': 'image/svg+xml', 'href': lambda request: static('web/admin-icon.svg')},
        {'rel': 'icon', 'sizes': '48x48', 'type': 'image/png', 'href': lambda request: static('web/admin-icon-48.png')},
        {'rel': 'apple-touch-icon', 'href': lambda request: static('web/admin-apple-touch-icon.png')},
    ],
    'SITE_URL': '/',
    'DASHBOARD_CALLBACK': 'config.dashboard.dashboard_callback',
    'COLORS': {
        'base': {
            '50': 'oklch(98.8% .007 87)',
            '100': 'oklch(96.5% .008 87)',
            '200': 'oklch(92.5% .012 87)',
            '300': 'oklch(86% .02 87)',
            '400': 'oklch(70% .02 87)',
            '500': 'oklch(55% .018 87)',
            '600': 'oklch(44.5% .017 87)',
            '700': 'oklch(36% .015 87)',
            '800': 'oklch(27% .011 87)',
            '900': 'oklch(21% .009 87)',
            '950': 'oklch(13% .007 87)',
        },
        'primary': {
            '50': 'oklch(97.5% .012 73.5)',
            '100': 'oklch(94.5% .025 73.5)',
            '200': 'oklch(89.5% .045 73.5)',
            '300': 'oklch(82% .07 73.5)',
            '400': 'oklch(71% .09 73.5)',
            '500': 'oklch(61% .098 73.5)',
            '600': 'oklch(51.9% .097 73.5)',
            '700': 'oklch(45% .085 73.5)',
            '800': 'oklch(38.5% .07 73.5)',
            '900': 'oklch(32% .056 73.5)',
            '950': 'oklch(23% .04 73.5)',
        },
    },
    'SIDEBAR': {
        'show_search': False,
        'show_all_applications': False,
        'navigation': [
            {
                'title': 'Studio',
                'items': [
                    {'title': 'Dashboard', 'icon': 'dashboard', 'link': reverse_lazy('admin:index')},
                    {
                        'title': 'Works',
                        'icon': 'palette',
                        'link': reverse_lazy('admin:artworks_artwork_changelist'),
                        'active': 'config.dashboard.works_active',
                    },
                    {'title': 'Home page', 'icon': 'home', 'link': reverse_lazy('admin:artworks_homepage')},
                    {'title': 'Wall scenes', 'icon': 'wallpaper', 'link': reverse_lazy('admin:artworks_roomscene_changelist')},
                    {
                        'title': 'Orders',
                        'icon': 'local_shipping',
                        'link': reverse_lazy('admin:commerce_order_changelist'),
                        'badge': 'config.dashboard.orders_to_ship',
                    },
                    {
                        'title': 'Enquiries',
                        'icon': 'mail',
                        'link': reverse_lazy('admin:enquiries_enquiry_changelist'),
                        'badge': 'config.dashboard.unread_enquiries',
                    },
                    {'title': 'Mailing list', 'icon': 'contact_mail', 'link': reverse_lazy('admin:enquiries_subscriber_changelist')},
                    {
                        'title': 'Site text',
                        'icon': 'edit_note',
                        'link': reverse_lazy('admin:content_sitecontent_changelist'),
                        'active': 'config.dashboard.site_text_active',
                    },
                    {'title': 'Appearance', 'icon': 'brush', 'link': reverse_lazy('admin:content_appearance')},
                    {'title': 'Pages', 'icon': 'gavel', 'link': reverse_lazy('admin:content_page_changelist')},
                ],
            },
            {
                'title': 'Accounts',
                'collapsible': True,
                'items': [
                    {'title': 'Users', 'icon': 'person', 'link': reverse_lazy('admin:auth_user_changelist')},
                ],
            },
        ],
    },
}

INERTIA_LAYOUT = 'index.html'

WSGI_APPLICATION = 'config.wsgi.application'

DJANGO_VITE = {
    'default': {
        'dev_mode': DEBUG,
        'manifest_path': BASE_DIR / 'frontend/dist/manifest.json',
    }
}


DATABASES = {'default': env.db('DATABASE_URL')}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-gb'

TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [] if DEBUG else [BASE_DIR / 'frontend/dist']

AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME', default='')

STORAGES = {
    'default': {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {
            'bucket_name': AWS_STORAGE_BUCKET_NAME,
            'region_name': 'eu-west-2',
            'querystring_auth': False,
            'file_overwrite': False,
            'object_parameters': {'CacheControl': 'public, max-age=86400'},
        },
    }
    if AWS_STORAGE_BUCKET_NAME
    else {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}

WHITENOISE_IMMUTABLE_FILE_TEST = r'^.+-[0-9a-zA-Z_-]{8}\.[a-z0-9]+$'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='Joe Burgess <hello@joeburgess.dev>')

MAILGUN_API_KEY = env('MAILGUN_API_KEY', default='')

MAILERS = {
    'default': {
        'BACKEND': 'anymail.backends.mailgun.EmailBackend',
        'OPTIONS': {
            'api_key': MAILGUN_API_KEY,
            'sender_domain': env('MAILGUN_SENDER_DOMAIN', default='mail.elisebeer.art'),
            'api_url': 'https://api.eu.mailgun.net/v3',
        },
    }
    if MAILGUN_API_KEY
    else {'BACKEND': 'django.core.mail.backends.console.EmailBackend'},
}

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = env('STRIPE_WEBHOOK_SECRET', default='')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'root': {'handlers': ['console'], 'level': 'INFO'},
    'loggers': {'stripe': {'level': 'WARNING'}},
}

SENTRY_DSN = env('SENTRY_DSN', default='')
SENTRY_FRONTEND_DSN = env('SENTRY_FRONTEND_DSN', default='')
SENTRY_ENVIRONMENT = env('SENTRY_ENVIRONMENT', default='production')

if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=SENTRY_ENVIRONMENT,
        send_default_pii=False,
        traces_sample_rate=0.1,
    )
