# Generated by Django 6.1.1 on 2026-09-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(blank=True, help_text='Large statement on About page')),
                ('biography', models.TextField(blank=True, help_text='About page content. Blank lines start new paragraphs.')),
            ],
            options={
                'verbose_name': 'site content',
                'verbose_name_plural': 'site content',
            },
        ),
    ]
