# Generated by Django 6.1.1 on 2026-09-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0001_schema_initial_site_content_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='contact_details',
            field=models.TextField(blank=True, help_text='Contact page. Line breaks are kept.'),
        ),
    ]
