# Generated by Django 6.1.1 on 2026-09-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_schema_contact_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='Where contact form enquiries are sent.', max_length=254),
        ),
    ]
