# Generated by Django 6.1.1 on 2026-09-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_schema_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='intro',
            field=models.TextField(blank=True, help_text='Short text in the home page sidebar.'),
        ),
    ]
