# Generated by Django 6.1.1 on 2026-09-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_schema_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='delivery_pence',
            field=models.PositiveIntegerField(default=0, help_text='Flat UK delivery charge added at checkout.'),
        ),
    ]
