# Generated by Django 6.1.1 on 2026-09-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_schema_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='site_description',
            field=models.CharField(blank=True, help_text='Default text for search results and link previews.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='site_name',
            field=models.CharField(default='Gesso', help_text='Shown in the header, browser tabs and the admin.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='tagline',
            field=models.CharField(blank=True, help_text='Shown under the name in the header.', max_length=100),
        ),
    ]
