# Generated by Django 6.1.1 on 2026-09-26 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_schema_site_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variants', models.JSONField(default=list, editable=False)),
                ('original', models.ImageField(upload_to='about/originals/')),
                ('alt', models.CharField(help_text='Describe the photo for people using screen readers.', max_length=200, verbose_name='alt text')),
                ('caption', models.CharField(blank=True, help_text='Shown under the photo, for example a photo credit.', max_length=200)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('site_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_images', to='content.sitecontent')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
    ]
