# Generated by Django 6.1.1 on 2026-09-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_schema_about_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='headings',
            field=models.CharField(choices=[('serif', 'Classic serif'), ('sans', 'Modern sans')], default='serif', max_length=20),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='layout',
            field=models.CharField(choices=[('rail', 'Side rail'), ('top', 'Top bar')], default='rail', help_text='Where the name and menu sit.', max_length=20),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='motion',
            field=models.BooleanField(default=True, help_text='Images fade in and pages ease in. Always off for visitors who ask for reduced motion.', verbose_name='gentle motion'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='theme',
            field=models.CharField(choices=[('paper', 'Paper'), ('gallery', 'Gallery'), ('charcoal', 'Charcoal'), ('slate', 'Slate')], default='paper', help_text='Colours for the whole site. Artwork is never tinted.', max_length=20),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='work_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('salon', 'Salon'), ('stack', 'Exhibition')], default='grid', help_text='How the full list of works is arranged.', max_length=20),
        ),
    ]
