# Generated by Django 6.1.1 on 2026-09-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_schema_appearance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontent',
            name='theme',
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='motion',
            field=models.BooleanField(default=True, help_text='Images fade in, pages ease in and pictures zoom a little on hover. Always off for visitors who ask for reduced motion.', verbose_name='gentle motion'),
        ),
    ]
