# Generated by Django 6.1.1 on 2026-09-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_schema_visitor_chooses_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='about_layout',
            field=models.CharField(choices=[('beside', 'Portrait beside statement'), ('above', 'Portrait above')], default='beside', help_text='How the About page is arranged.', max_length=20),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='show_index',
            field=models.BooleanField(default=True, help_text='A list of every work under the featured ones.', verbose_name='index of works on the home page'),
        ),
    ]
