# Generated by Django 6.1.1 on 2026-09-26 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_schema_index_and_about_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='For example Instagram.', max_length=50)),
                ('url', models.URLField(verbose_name='link')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('site_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='content.sitecontent')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
    ]
