# Generated by Django 6.1.1 on 2026-09-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_schema_social_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='The end of the web address. Checkout links to "terms" and the mailing list to "privacy".', unique=True)),
                ('body', models.TextField(help_text='Blank lines start new paragraphs. Start a paragraph with ## to make it a heading.')),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
    ]
