# Generated by Django 6.1.1 on 2026-09-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_data_legal_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='theme',
            field=models.CharField(choices=[('paper', 'Paper'), ('gallery', 'Gallery'), ('slate', 'Slate')], default='paper', help_text='Colours for the whole site. Visitors can switch between its light and dark versions. Artwork is never tinted.', max_length=20),
        ),
    ]
