# Generated by Django 6.1.1 on 2026-09-27 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_data_legal_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('solo', 'Solo exhibitions'), ('group', 'Group exhibitions'), ('award', 'Awards'), ('collection', 'Collections'), ('education', 'Education')], default='group', max_length=20, verbose_name='type')),
                ('title', models.CharField(max_length=200)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('place', models.CharField(blank=True, help_text='Town or city.', max_length=100)),
                ('link', models.URLField(blank=True)),
                ('site_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_entries', to='content.sitecontent')),
            ],
            options={
                'verbose_name': 'CV entry',
                'verbose_name_plural': 'CV entry',
                'ordering': ('-year', 'pk'),
            },
        ),
    ]
