# Generated by Django 6.1.1 on 2026-09-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_schema_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='italic_titles',
            field=models.BooleanField(default=False, help_text='Set work titles in italic, as in a catalogue.', verbose_name='italic artwork titles'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='headings',
            field=models.CharField(choices=[('serif', 'Caslon'), ('garamond', 'Garamond'), ('sans', 'Modern sans')], default='serif', max_length=20),
        ),
    ]
