# Generated by Django 6.1.1 on 2026-09-28 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_schema_typefaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
            ],
            options={
                'verbose_name': 'settings',
                'verbose_name_plural': 'settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.sitecontent',),
        ),
    ]
