# Generated by Django 6.1.1 on 2026-09-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_schema_initial_enquiry_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='topic',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('buying', 'Buying a work'), ('commission', 'Commission'), ('press', 'Exhibitions & press')], default='general', max_length=20),
        ),
    ]
