# Generated by Django 6.1.1 on 2026-09-28 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artworks', '0021_schema_wall_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReferrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('host', models.CharField(max_length=255)),
                ('visits', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('day', 'host'), name='unique_daily_referrer')],
            },
        ),
        migrations.CreateModel(
            name='DailyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('path', models.CharField(max_length=255)),
                ('views', models.PositiveIntegerField(default=0)),
                ('artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_views', to='artworks.artwork')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('day', 'path'), name='unique_daily_view')],
            },
        ),
    ]
