# Generated by Django 6.1.1 on 2026-09-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_schema_daily_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('visitors', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'daily visitors',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('visitor', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=255)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('day', 'visitor', 'path'), name='unique_visit')],
            },
        ),
    ]
