# Generated by Django 6.1.1 on 2026-09-28 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_schema_daily_visitors'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='visit',
            name='unique_visit',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
