# Generated by Django 6.1.1 on 2026-09-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('artworks', '0002_schema__artworkimage_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkimage',
            name='variants',
            field=models.JSONField(default=list, editable=False),
        ),
    ]
