# Generated by Django 6.1.1 on 2026-09-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('artworks', '0003_schema_image_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='height_mm',
            field=models.PositiveIntegerField(default=700),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='medium',
            field=models.CharField(default='Oil on canvas', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='width_mm',
            field=models.PositiveIntegerField(default=500),
            preserve_default=False,
        ),
    ]
