# Generated by Django 6.1.1 on 2026-09-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('artworks', '0005_schema_status_and_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
