# Generated by Django 6.1.1 on 2026-09-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_schema_artwork_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='featured_order',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Show on the home page. Lower numbers come first.', null=True),
        ),
    ]
