# Generated by Django 6.1.1 on 2026-09-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0007_schema_featured_position'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='artwork',
            name='artwork_available_needs_price',
        ),
        migrations.AddField(
            model_name='artwork',
            name='reserved_until',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('not_for_sale', 'Not for sale')], default='not_for_sale', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='artwork',
            constraint=models.CheckConstraint(condition=models.Q(('price_pence__isnull', True), ('status__in', ('available', 'reserved')), _negated=True), name='artwork_for_sale_needs_price', violation_error_message='A work for sale needs a price.'),
        ),
    ]
