# Generated by Django 6.1.1 on 2026-09-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0008_schema_reserved'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='artwork',
            name='artwork_for_sale_needs_price',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('not_for_sale', 'Not for sale')], default='not_for_sale', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='artwork',
            constraint=models.CheckConstraint(condition=models.Q(('price_pence__isnull', True), ('status', 'available'), _negated=True), name='artwork_available_needs_price', violation_error_message='An available work needs a price.'),
        ),
    ]
