# Generated by Django 6.1.1 on 2026-09-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0010_schema_home_page_spot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artworkimage',
            options={'ordering': ('is_process', 'position', 'pk')},
        ),
        migrations.AddField(
            model_name='artworkimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Shown under process photos, e.g. "Drying in the yard".', max_length=200),
        ),
        migrations.AddField(
            model_name='artworkimage',
            name='is_process',
            field=models.BooleanField(default=False, help_text='Show in "In the studio" rather than as a view of the finished work.', verbose_name='studio / process photo'),
        ),
    ]
