# Generated by Django 6.1.1 on 2026-09-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0011_schema_image_caption_and_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='featured_order',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 (large hero)'), (2, '2')], help_text='Leave empty to keep this work off the home page.', null=True, unique=True, verbose_name='home page spot'),
        ),
    ]
