# Generated by Django 6.1.1 on 2026-09-26 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0013_data_clear_home_page_spot_three'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='artworkimage',
            name='home_position',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='artworkimage',
            name='artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='artworks.artwork'),
        ),
    ]
