# Generated by Django 6.1.1 on 2026-09-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0015_data_keep_current_studio_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkimage',
            name='alt',
            field=models.CharField(blank=True, help_text='Describe the image for people using screen readers.', max_length=200, verbose_name='alt text'),
        ),
    ]
