# Generated by Django 6.1.1 on 2026-09-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0016_schema_image_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='framing',
            field=models.CharField(blank=True, help_text='For example "Framed in oak" or "Unframed, ready to hang".', max_length=200),
        ),
    ]
