# Generated by Django 6.1.1 on 2026-09-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0017_schema_framing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ('position', '-year', 'title')},
        ),
        migrations.AddField(
            model_name='artwork',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
