# Generated by Django 6.1.1 on 2026-09-27 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0019_data_keep_newest_first'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormerSlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='former_slugs', to='artworks.artwork')),
            ],
        ),
    ]
