# Generated by Django 6.1.1 on 2026-09-27 12:43

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0020_schema_former_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(help_text='A front-on photo of a wall, ideally at least 2400px wide.', upload_to='scenes/')),
                ('px_per_cm', models.DecimalField(decimal_places=2, help_text='Measure something of known size on the wall in the full-size photo.', max_digits=6, verbose_name='pixels per cm')),
                ('anchor_x', models.DecimalField(decimal_places=2, default=Decimal(50), max_digits=5, verbose_name='centre across (%)')),
                ('anchor_y', models.DecimalField(decimal_places=2, default=Decimal(40), max_digits=5, verbose_name='centre down (%)')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='artworkimage',
            name='scene',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wall_views', to='artworks.roomscene'),
        ),
    ]
